---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1m0s
  ref:
    branch: main
  secretref:
    name: github-instavote
  url: https://github.com/dopsdemo/instavote-deploy.git

